import { capitalize } from './wizardSteps.js'

function todayLabel() {
  return new Date().toLocaleDateString(undefined, {
    weekday: 'long',
    month: 'long',
    day: 'numeric',
    year: 'numeric',
  })
}

function nowTimeLabel() {
  return new Date().toLocaleTimeString(undefined, {
    hour: 'numeric',
    minute: '2-digit',
  })
}

/** Angela Roell / SARE-style detailed inspection (Q1–Q57). */
export const DETAILED_WIZARD_STEPS = [
  {
    id: 'q1',
    field: 'inspectionDate',
    type: 'qa',
    section: '1. Header',
    title: 'Q1. Date of inspection',
    question: 'What is the date of inspection?',
    prompt: 'Say next to keep today, or enter the date then next.',
  },
  {
    id: 'q2',
    field: 'yard',
    type: 'qa',
    section: '1. Header',
    title: 'Q2. Yard',
    question: 'Which yard is this hive located in?',
    prompt: 'Answer, then next.',
  },
  {
    id: 'q3',
    field: 'hiveName',
    type: 'qa',
    section: '1. Header',
    title: 'Q3. Hive ID',
    question: 'What is the Hive ID?',
    prompt: 'Say next to keep the selected hive, or enter another ID.',
  },
  {
    id: 'q4',
    field: 'weatherToday',
    type: 'qa',
    section: '1. Header',
    title: 'Q4. Weather today',
    question: 'What is the weather today?',
    prompt: 'Answer freely, or tap an option.',
    options: ['clear', 'cloudy', 'rain', 'windy'],
  },
  {
    id: 'q5',
    field: 'weatherRecently',
    type: 'qa',
    section: '1. Header',
    title: 'Q5. Weather recently',
    question: 'What has the weather been recently?',
    prompt: 'Answer, then next.',
  },
  {
    id: 'q6',
    field: 'inspector',
    type: 'qa',
    section: '1. Header',
    title: 'Q6. Inspector',
    question: 'Who is the inspector?',
    prompt: 'Say the name, then next.',
  },
  {
    id: 'q7',
    field: 'nextInspectionDue',
    type: 'qa',
    section: '1. Header',
    title: 'Q7. Next inspection due',
    question: 'When is the next inspection due?',
    prompt: 'Answer, then next.',
  },

  {
    id: 'q8',
    field: 'temperament',
    type: 'qa',
    section: '2. Hive Temperament',
    title: 'Q8. Hive temperament',
    question: 'What is the hive temperament?',
    prompt: 'Select one, then next.',
    options: ['Calm', 'Nervous', 'Aggressive'],
  },

  {
    id: 'q9',
    field: 'queenLocated',
    type: 'qa',
    section: '3. Queen Status',
    title: 'Q9. Queen located',
    question: 'Was the queen located?',
    prompt: 'Select yes or no.',
    options: ['Yes', 'No'],
  },
  {
    id: 'q10',
    field: 'queenMarked',
    type: 'qa',
    section: '3. Queen Status',
    title: 'Q10. Queen marked',
    question: 'Is the queen marked?',
    prompt: 'Select yes or no.',
    options: ['Yes', 'No'],
  },
  {
    id: 'q11',
    field: 'queenColor',
    type: 'qa',
    section: '3. Queen Status',
    title: 'Q11. Queen color',
    question: 'If marked, what is the color?',
    prompt: 'Say the color, or skip.',
  },
  {
    id: 'q12',
    field: 'queenReplacementDate',
    type: 'qa',
    section: '3. Queen Status',
    title: 'Q12. Queen replacement date',
    question: 'Queen replacement date, if applicable?',
    prompt: 'Enter a date, or skip.',
  },

  {
    id: 'q13',
    field: 'broodFrames',
    type: 'qa',
    section: '4. Brood Pattern',
    title: 'Q13. Brood frames',
    question: 'How many frames contain brood?',
    prompt: 'Say the number, then next.',
  },
  {
    id: 'q14',
    field: 'layingPattern',
    type: 'qa',
    section: '4. Brood Pattern',
    title: 'Q14. Laying pattern',
    question: 'How would you describe the laying pattern?',
    prompt: 'Select one, then next.',
    options: [
      'Beautiful – Solid & Uniform',
      'Good – Describe',
      'Hygienic – Spotty due to hygienic behavior',
      'Mediocre – Intermittent',
      'Poor – Spotty',
    ],
  },
  {
    id: 'q15',
    field: 'eggsPresent',
    type: 'qa',
    section: '4. Brood Pattern',
    title: 'Q15. Eggs present',
    question: 'Are eggs present?',
    prompt: 'Select yes or no.',
    options: ['Yes', 'No'],
  },

  {
    id: 'q16',
    field: 'populationLevel',
    type: 'qa',
    section: '5. Population Strength',
    title: 'Q16. Population level',
    question: 'What is the population level?',
    prompt: 'Select one.',
    options: ['Heavy', 'Good', 'Moderate', 'Low'],
  },
  {
    id: 'q17',
    field: 'framesFullOfBees',
    type: 'qa',
    section: '5. Population Strength',
    title: 'Q17. Frames full of bees',
    question: 'Number of frames full of bees?',
    prompt: 'Say the number, then next.',
  },

  {
    id: 'q18',
    field: 'broodFramesRotated',
    type: 'qa',
    section: '6. Hive Management Actions',
    title: 'Q18. Brood frames rotated',
    question: 'Were brood frames rotated?',
    prompt: 'Select yes or no.',
    options: ['Yes', 'No'],
  },
  {
    id: 'q19',
    field: 'additionalHiveBody',
    type: 'qa',
    section: '6. Hive Management Actions',
    title: 'Q19. Additional hive body',
    question: 'Was an additional hive body added?',
    prompt: 'Select yes or no.',
    options: ['Yes', 'No'],
  },
  {
    id: 'q20',
    field: 'hiveSplit',
    type: 'qa',
    section: '6. Hive Management Actions',
    title: 'Q20. Hive split',
    question: 'Was the hive split? If yes, what is the new hive number?',
    prompt: 'Say no, or yes and the new hive number.',
  },
  {
    id: 'q21',
    field: 'swarmingImminent',
    type: 'qa',
    section: '6. Hive Management Actions',
    title: 'Q21. Swarming imminent',
    question: 'Is swarming imminent?',
    prompt: 'Select yes or no.',
    options: ['Yes', 'No'],
  },

  {
    id: 'q22',
    field: 'excessiveDroneCells',
    type: 'qa',
    section: '7. Drone Cells & Queen Cells',
    title: 'Q22. Excessive drone cells',
    question: 'Are excessive drone cells present?',
    prompt: 'Select yes or no.',
    options: ['Yes', 'No'],
  },
  {
    id: 'q23',
    field: 'dronePopulation',
    type: 'qa',
    section: '7. Drone Cells & Queen Cells',
    title: 'Q23. Drone population',
    question: 'Drone population estimate?',
    prompt: 'Select one.',
    options: ['Low (≤30)', 'Average (30–100)', 'High (100+)'],
  },
  {
    id: 'q24',
    field: 'queenCellsPresent',
    type: 'qa',
    section: '7. Drone Cells & Queen Cells',
    title: 'Q24. Queen cells present',
    question: 'Queen cells present?',
    prompt: 'Select yes or no.',
    options: ['Yes', 'No'],
  },
  {
    id: 'q25',
    field: 'queenCellsFrameBottom',
    type: 'qa',
    section: '7. Drone Cells & Queen Cells',
    title: 'Q25. Queen cells along frame bottom',
    question: 'Queen cells along frame bottom — how many?',
    prompt: 'Say the number, or skip.',
  },
  {
    id: 'q26',
    field: 'convertedWorkerQueenCells',
    type: 'qa',
    section: '7. Drone Cells & Queen Cells',
    title: 'Q26. Converted worker cell queen cells',
    question: 'Converted worker cell queen cells — how many?',
    prompt: 'Say the number, or skip.',
  },

  {
    id: 'q27',
    field: 'honeyNectarLevels',
    type: 'qa',
    section: '8. Food Stores',
    title: 'Q27. Honey / nectar levels',
    question: 'Honey and nectar levels?',
    prompt: 'Select one.',
    options: [
      'High (everywhere)',
      'Average',
      'Low',
      'Near brood',
      'Moved/manipulated',
    ],
  },
  {
    id: 'q28',
    field: 'pollenLevels',
    type: 'qa',
    section: '8. Food Stores',
    title: 'Q28. Pollen levels',
    question: 'Pollen levels?',
    prompt: 'Select one.',
    options: ['High', 'Average', 'Low'],
  },

  {
    id: 'q29',
    field: 'diseaseOrPests',
    type: 'qa',
    section: '9. Disease & Pests',
    title: 'Q29. Disease or pests present',
    question: 'Any disease or pests present?',
    prompt: 'Select yes or no.',
    options: ['Yes', 'No'],
  },
  {
    id: 'q30',
    field: 'diseaseIdentify',
    type: 'multi',
    section: '9. Disease & Pests',
    title: 'Q30. Identify disease / pests',
    question: 'If yes, identify (select all that apply).',
    prompt: 'Tap all that apply, then next. Or skip.',
    options: [
      'Chalkbrood',
      'AFB',
      'EFB',
      'Varroa mites',
      'Tracheal mites',
      'Small hive beetles',
      'Deformed wing',
      'Hairless bees',
      'Stunted',
      'Unknown',
    ],
  },

  {
    id: 'q31',
    field: 'treatmentAddedDate',
    type: 'qa',
    section: '10. Medications / Treatments',
    title: 'Q31. Treatment added date',
    question: 'Treatment added date?',
    prompt: 'Enter a date, or skip.',
  },
  {
    id: 'q32',
    field: 'treatmentRemovalDate',
    type: 'qa',
    section: '10. Medications / Treatments',
    title: 'Q32. Treatment removal date',
    question: 'Treatment removal date?',
    prompt: 'Enter a date, or skip.',
  },
  {
    id: 'q33',
    field: 'treatmentType',
    type: 'qa',
    section: '10. Medications / Treatments',
    title: 'Q33. Type of treatment',
    question: 'Type of treatment?',
    prompt: 'Answer, or skip.',
  },

  {
    id: 'q34',
    field: 'screenedBottomInsert',
    type: 'qa',
    section: '11. Varroa IPM Checks',
    title: 'Q34. Screened bottom insert',
    question: 'Screened bottom insert position?',
    prompt: 'Select IN or OUT.',
    options: ['IN', 'OUT'],
  },
  {
    id: 'q35',
    field: 'screenedBottomNotes',
    type: 'qa',
    section: '11. Varroa IPM Checks',
    title: 'Q35. Bottom board check',
    question: 'Screened bottom board check notes?',
    prompt: 'Answer, or skip.',
  },
  {
    id: 'q36',
    field: 'powderedSugarRoll',
    type: 'qa',
    section: '11. Varroa IPM Checks',
    title: 'Q36. Powdered sugar roll',
    question: 'Powdered sugar roll mite drop?',
    prompt: 'Answer, or skip.',
  },
  {
    id: 'q37',
    field: 'droneBroodCheck',
    type: 'qa',
    section: '11. Varroa IPM Checks',
    title: 'Q37. Drone brood check',
    question: 'Drone brood check?',
    prompt: 'Answer, or skip.',
  },
  {
    id: 'q38',
    field: 'alcoholWash',
    type: 'qa',
    section: '11. Varroa IPM Checks',
    title: 'Q38. Alcohol wash',
    question: 'Alcohol wash mite drop?',
    prompt: 'Answer, or skip.',
  },

  {
    id: 'q39',
    field: 'pollenSubstitute',
    type: 'qa',
    section: '12. Spring Feeding / Build-Up',
    title: 'Q39. Pollen substitute',
    question: 'Pollen substitute used?',
    prompt: 'Select one.',
    options: ['Dry', 'Patties', 'None'],
  },
  {
    id: 'q40',
    field: 'sugarSyrup11',
    type: 'qa',
    section: '12. Spring Feeding / Build-Up',
    title: 'Q40. Sugar syrup 1:1',
    question: 'Sugar syrup 1:1 ratio amount?',
    prompt: 'Answer, or skip.',
  },

  {
    id: 'q41',
    field: 'supersAdded',
    type: 'qa',
    section: '13. Honey Flow Preparation',
    title: 'Q41. Supers added',
    question: 'Supers added — how many deep, medium, and shallow?',
    prompt: 'Example: D 1, M 2, S 0',
  },
  {
    id: 'q42',
    field: 'pollenTrapAdded',
    type: 'qa',
    section: '13. Honey Flow Preparation',
    title: 'Q42. Pollen trap',
    question: 'Pollen trap added?',
    prompt: 'Select yes or no.',
    options: ['Yes', 'No'],
  },

  {
    id: 'q43',
    field: 'supersRemoved',
    type: 'qa',
    section: '14. Honey Removal / Extraction',
    title: 'Q43. Supers removed',
    question: 'Number of supers removed?',
    prompt: 'Say the number, or skip.',
  },
  {
    id: 'q44',
    field: 'honeyExtractionLbs',
    type: 'qa',
    section: '14. Honey Removal / Extraction',
    title: 'Q44. Honey for extraction',
    question: 'Pounds of honey for extraction?',
    prompt: 'Answer, or skip.',
  },
  {
    id: 'q45',
    field: 'honeyCutCombLbs',
    type: 'qa',
    section: '14. Honey Removal / Extraction',
    title: 'Q45. Honey for cut comb',
    question: 'Pounds of honey for cut comb?',
    prompt: 'Answer, or skip.',
  },

  {
    id: 'q46',
    field: 'winterScreenedBottom',
    type: 'qa',
    section: '15. Winter Preparation',
    title: 'Q46. Winter screened bottom',
    question: 'Winter screened bottom insert?',
    prompt: 'Select IN or OUT.',
    options: ['IN', 'OUT'],
  },
  {
    id: 'q47',
    field: 'homasoteInsulation',
    type: 'qa',
    section: '15. Winter Preparation',
    title: 'Q47. Homasote insulation',
    question: 'Homasote insulation added?',
    prompt: 'Select yes or no.',
    options: ['Yes', 'No'],
  },
  {
    id: 'q48',
    field: 'hiveWrapped',
    type: 'qa',
    section: '15. Winter Preparation',
    title: 'Q48. Hive wrapped',
    question: 'Hive wrapped?',
    prompt: 'Select yes or no.',
    options: ['Yes', 'No'],
  },
  {
    id: 'q49',
    field: 'entranceReducer',
    type: 'qa',
    section: '15. Winter Preparation',
    title: 'Q49. Entrance reducer / mouse guard',
    question: 'Entrance reducer or mouse guard installed?',
    prompt: 'Select yes or no.',
    options: ['Yes', 'No'],
  },
  {
    id: 'q50',
    field: 'winterFeeding',
    type: 'qa',
    section: '15. Winter Preparation',
    title: 'Q50. Winter feeding type',
    question: 'Winter feeding type?',
    prompt: 'Select one.',
    options: ['Syrup 2:1', 'Pollen', 'Candy', 'Dry sugar'],
  },

  {
    id: 'q51',
    field: 'colonyConfig',
    type: 'qa',
    section: '16. Colony Configuration',
    title: 'Q51. Colony configuration',
    question: 'Colony configuration — deep, medium, and shallow counts?',
    prompt: 'Example: D 2, M 1, S 0',
  },

  {
    id: 'q52',
    field: 'hiveCondition',
    type: 'qa',
    section: '17. Hive Condition',
    title: 'Q52. Hive condition',
    question: 'Hive condition?',
    prompt: 'Select one.',
    options: ['Normal', 'Brace comb', 'Burr comb'],
  },
  {
    id: 'q53',
    field: 'propolisLevel',
    type: 'qa',
    section: '17. Hive Condition',
    title: 'Q53. Propolis level',
    question: 'Propolis level?',
    prompt: 'Select one.',
    options: ['High', 'Average', 'Low'],
  },
  {
    id: 'q54',
    field: 'odor',
    type: 'qa',
    section: '17. Hive Condition',
    title: 'Q54. Odor',
    question: 'Odor?',
    prompt: 'Select one.',
    options: ['Foul', 'Strange', 'Normal'],
  },
  {
    id: 'q55',
    field: 'framesNeedingReplacement',
    type: 'qa',
    section: '17. Hive Condition',
    title: 'Q55. Frames needing replacement',
    question: 'Frames needing replacement — how many?',
    prompt: 'Say the number, or skip.',
  },
  {
    id: 'q56',
    field: 'equipmentNeedingReplacement',
    type: 'qa',
    section: '17. Hive Condition',
    title: 'Q56. Equipment needing replacement',
    question: 'Equipment needing replacement?',
    prompt: 'Answer, or skip.',
  },
  {
    id: 'q57',
    field: 'replacementReason',
    type: 'qa',
    section: '17. Hive Condition',
    title: 'Q57. Reason for replacement',
    question: 'Reason for replacement?',
    prompt: 'Answer, then say save or skip.',
  },
]

export function emptyDetailedForm(hive) {
  const blank = Object.fromEntries(
    DETAILED_WIZARD_STEPS.map((step) => [step.field, '']),
  )
  return {
    ...blank,
    inspectionDate: todayLabel(),
    inspectionTime: nowTimeLabel(),
    hiveName: hive?.name ?? '',
    yard: hive?.location ?? '',
    location: hive?.location ?? '',
  }
}

export function buildDetailedQuestionSpeech(step, stepIndex) {
  const num = stepIndex + 1
  const total = DETAILED_WIZARD_STEPS.length
  const suggestions =
    step.type === 'multi'
      ? ` Select all that apply: ${step.options.join(', ')}. Then say next.`
      : step.options?.length
        ? ` Options: ${step.options.join(', ')}.`
        : ' Answer in your own words, then say next.'
  return `Detailed inspection. Question ${num} of ${total}. ${step.section}. ${step.question}${suggestions}`
}

export function buildDetailedConfirmation(step, value) {
  if (value) return `${step.title}: ${value}.`
  return `${step.title} skipped.`
}

export const DETAILED_HISTORY_SECTIONS = [
  {
    title: 'Header',
    fields: [
      ['Date', 'inspectionDate'],
      ['Yard', 'yard'],
      ['Hive ID', 'hiveName'],
      ['Weather today', 'weatherToday'],
      ['Weather recently', 'weatherRecently'],
      ['Inspector', 'inspector'],
      ['Next inspection', 'nextInspectionDue'],
    ],
  },
  {
    title: 'Temperament & queen',
    fields: [
      ['Temperament', 'temperament'],
      ['Queen located', 'queenLocated'],
      ['Queen marked', 'queenMarked'],
      ['Queen color', 'queenColor'],
      ['Queen replacement', 'queenReplacementDate'],
    ],
  },
  {
    title: 'Brood & population',
    fields: [
      ['Brood frames', 'broodFrames'],
      ['Laying pattern', 'layingPattern'],
      ['Eggs', 'eggsPresent'],
      ['Population', 'populationLevel'],
      ['Frames of bees', 'framesFullOfBees'],
    ],
  },
  {
    title: 'Management',
    fields: [
      ['Brood rotated', 'broodFramesRotated'],
      ['Hive body added', 'additionalHiveBody'],
      ['Hive split', 'hiveSplit'],
      ['Swarming imminent', 'swarmingImminent'],
    ],
  },
  {
    title: 'Drone & queen cells',
    fields: [
      ['Excessive drone cells', 'excessiveDroneCells'],
      ['Drone population', 'dronePopulation'],
      ['Queen cells', 'queenCellsPresent'],
      ['Along frame bottom', 'queenCellsFrameBottom'],
      ['Converted worker cells', 'convertedWorkerQueenCells'],
    ],
  },
  {
    title: 'Stores',
    fields: [
      ['Honey / nectar', 'honeyNectarLevels'],
      ['Pollen', 'pollenLevels'],
    ],
  },
  {
    title: 'Disease, pests & treatment',
    fields: [
      ['Disease/pests present', 'diseaseOrPests'],
      ['Identified', 'diseaseIdentify'],
      ['Treatment added', 'treatmentAddedDate'],
      ['Treatment removed', 'treatmentRemovalDate'],
      ['Treatment type', 'treatmentType'],
    ],
  },
  {
    title: 'Varroa IPM',
    fields: [
      ['Screened bottom', 'screenedBottomInsert'],
      ['Bottom board notes', 'screenedBottomNotes'],
      ['Sugar roll', 'powderedSugarRoll'],
      ['Drone brood check', 'droneBroodCheck'],
      ['Alcohol wash', 'alcoholWash'],
    ],
  },
  {
    title: 'Seasonal work',
    fields: [
      ['Pollen substitute', 'pollenSubstitute'],
      ['Syrup 1:1', 'sugarSyrup11'],
      ['Supers added', 'supersAdded'],
      ['Pollen trap', 'pollenTrapAdded'],
      ['Supers removed', 'supersRemoved'],
      ['Extraction lbs', 'honeyExtractionLbs'],
      ['Cut comb lbs', 'honeyCutCombLbs'],
    ],
  },
  {
    title: 'Winter & hive condition',
    fields: [
      ['Winter screened bottom', 'winterScreenedBottom'],
      ['Homasote', 'homasoteInsulation'],
      ['Wrapped', 'hiveWrapped'],
      ['Reducer / mouse guard', 'entranceReducer'],
      ['Winter feed', 'winterFeeding'],
      ['Colony config', 'colonyConfig'],
      ['Hive condition', 'hiveCondition'],
      ['Propolis', 'propolisLevel'],
      ['Odor', 'odor'],
      ['Frames to replace', 'framesNeedingReplacement'],
      ['Equipment to replace', 'equipmentNeedingReplacement'],
      ['Replacement reason', 'replacementReason'],
    ],
  },
]

export { capitalize }
